In [1]:
import torch 
import torch.nn as nn

In [2]:
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.f1 = nn.Linear(2,3)
        self.activ = nn.ReLU()
        self.name = "Valodic"
        self.tname = torch.Tensor(3,4)
        self.pname = nn.Parameter(torch.empty(4,5))

    def forward(self, x):
        return x    

In [3]:
model = MyModule()

In [4]:
model

MyModule(
  (f1): Linear(in_features=2, out_features=3, bias=True)
  (activ): ReLU()
)

In [5]:
model.f1

Linear(in_features=2, out_features=3, bias=True)

In [6]:
model.__dict__

{'training': True,
 '_parameters': OrderedDict([('pname', Parameter containing:
               tensor([[-3.7538e-34,  4.5636e-41, -3.7538e-34,  4.5636e-41,  0.0000e+00],
                       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -1.9005e-34,  4.5636e-41],
                       [ 3.4232e-03,  3.0767e-41, -7.6937e-29, -6.5114e+10, -1.9005e-34],
                       [ 4.5636e-41,  3.4494e-03,  3.0767e-41, -4.2634e-14, -3.3394e-27]],
                      requires_grad=True))]),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_post_hooks': OrderedDict(),
 '_modules': OrderedDict([('f1',
               Linear(in_features=2, out_features=3, bias=True)),
              ('activ', ReLU())]),
 'name': 'Valodic',
 'tname': tensor([[ 3.

In [9]:
model.f1

Linear(in_features=2, out_features=3, bias=True)

In [10]:
class SimpleModule:
    def __init__(self):
        ...

    def __setattr__(self, name, value):
        ...

    def __getattr__(self, name):
        ...

    def __call__(self):
        ...

    def __dir__(self):
        ...                

In [11]:
vars(model)

{'training': True,
 '_parameters': OrderedDict([('pname', Parameter containing:
               tensor([[-3.7538e-34,  4.5636e-41, -3.7538e-34,  4.5636e-41,  0.0000e+00],
                       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -1.9005e-34,  4.5636e-41],
                       [ 3.4232e-03,  3.0767e-41, -7.6937e-29, -6.5114e+10, -1.9005e-34],
                       [ 4.5636e-41,  3.4494e-03,  3.0767e-41, -4.2634e-14, -3.3394e-27]],
                      requires_grad=True))]),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_post_hooks': OrderedDict(),
 '_modules': OrderedDict([('f1',
               Linear(in_features=2, out_features=3, bias=True)),
              ('activ', ReLU())]),
 'name': 'Valodic',
 'tname': tensor([[ 3.

In [12]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_ver

In [13]:
model.__dict__

{'training': True,
 '_parameters': OrderedDict([('pname', Parameter containing:
               tensor([[-3.7538e-34,  4.5636e-41, -3.7538e-34,  4.5636e-41,  0.0000e+00],
                       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -1.9005e-34,  4.5636e-41],
                       [ 3.4232e-03,  3.0767e-41, -7.6937e-29, -6.5114e+10, -1.9005e-34],
                       [ 4.5636e-41,  3.4494e-03,  3.0767e-41, -4.2634e-14, -3.3394e-27]],
                      requires_grad=True))]),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_post_hooks': OrderedDict(),
 '_modules': OrderedDict([('f1',
               Linear(in_features=2, out_features=3, bias=True)),
              ('activ', ReLU())]),
 'name': 'Valodic',
 'tname': tensor([[ 3.

In [14]:
MyModule.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.MyModule.__init__(self)>,
              'forward': <function __main__.MyModule.forward(self, x)>,
              '__doc__': None})

In [15]:
vars(MyModule)

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.MyModule.__init__(self)>,
              'forward': <function __main__.MyModule.forward(self, x)>,
              '__doc__': None})

In [16]:
dir(MyModule)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_call_impl',
 '_get_backward_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_maybe_warn_non_full_backward_hook',
 '_named_members',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_version',
 'add_module',
 'apply',
 'bfloat16',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double',
 'dump_patches',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'get_buffer',
 'get_extra_state',
 'get_parameter',
 'get_submodule',
 'half',
 'ipu',